import { IConfig } from '../types';

export default {
  variables: {
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      'gray-100': '#f7fafc',
      'gray-200': '#edf2f7',
      'gray-300': '#e2e8f0',
      'gray-400': '#cbd5e0',
      'gray-500': '#a0aec0',
      'gray-600': '#718096',
      'gray-700': '#4a5568',
      'gray-800': '#2d3748',
      'gray-900': '#1a202c',
      'red-100': '#fff5f5',
      'red-200': '#fed7d7',
      'red-300': '#feb2b2',
      'red-400': '#fc8181',
      'red-500': '#f56565',
      'red-600': '#e53e3e',
      'red-700': '#c53030',
      'red-800': '#9b2c2c',
      'red-900': '#742a2a',
      'orange-100': '#fffaf0',
      'orange-200': '#feebc8',
      'orange-300': '#fbd38d',
      'orange-400': '#f6ad55',
      'orange-500': '#ed8936',
      'orange-600': '#dd6b20',
      'orange-700': '#c05621',
      'orange-800': '#9c4221',
      'orange-900': '#7b341e',
      'yellow-100': '#fffff0',
      'yellow-200': '#fefcbf',
      'yellow-300': '#faf089',
      'yellow-400': '#f6e05e',
      'yellow-500': '#ecc94b',
      'yellow-600': '#d69e2e',
      'yellow-700': '#b7791f',
      'yellow-800': '#975a16',
      'yellow-900': '#744210',
      'green-100': '#f0fff4',
      'green-200': '#c6f6d5',
      'green-300': '#9ae6b4',
      'green-400': '#68d391',
      'green-500': '#48bb78',
      'green-600': '#38a169',
      'green-700': '#2f855a',
      'green-800': '#276749',
      'green-900': '#22543d',
      'teal-100': '#e6fffa',
      'teal-200': '#b2f5ea',
      'teal-300': '#81e6d9',
      'teal-400': '#4fd1c5',
      'teal-500': '#38b2ac',
      'teal-600': '#319795',
      'teal-700': '#2c7a7b',
      'teal-800': '#285e61',
      'teal-900': '#234e52',
      'blue-100': '#ebf8ff',
      'blue-200': '#bee3f8',
      'blue-300': '#90cdf4',
      'blue-400': '#63b3ed',
      'blue-500': '#4299e1',
      'blue-600': '#3182ce',
      'blue-700': '#2b6cb0',
      'blue-800': '#2c5282',
      'blue-900': '#2a4365',
      'indigo-100': '#ebf4ff',
      'indigo-200': '#c3dafe',
      'indigo-300': '#a3bffa',
      'indigo-400': '#7f9cf5',
      'indigo-500': '#667eea',
      'indigo-600': '#5a67d8',
      'indigo-700': '#4c51bf',
      'indigo-800': '#434190',
      'indigo-900': '#3c366b',
      'purple-100': '#faf5ff',
      'purple-200': '#e9d8fd',
      'purple-300': '#d6bcfa',
      'purple-400': '#b794f4',
      'purple-500': '#9f7aea',
      'purple-600': '#805ad5',
      'purple-700': '#6b46c1',
      'purple-800': '#553c9a',
      'purple-900': '#44337a',
      'pink-100': '#fff5f7',
      'pink-200': '#fed7e2',
      'pink-300': '#fbb6ce',
      'pink-400': '#f687b3',
      'pink-500': '#ed64a6',
      'pink-600': '#d53f8c',
      'pink-700': '#b83280',
      'pink-800': '#97266d',
      'pink-900': '#702459',
    },
  },
  screens: {
    sm: css => `@media (max-width: 640px) {${css}}`,
    md: css => `@media (max-width: 768px) {${css}}`,
    lg: css => `@media (max-width: 1024px) {${css}}`,
    xl: css => `@media (max-width: 1280px) {${css}}`,
  },
  classnames: {
    block: () => '{display:block;}',
    'inline-block': () => '{display:inline-block;}',
    inline: () => '{display:inline;}',
    flex: () => '{display:flex;}',
    'inline-flex': () => '{display:inline-flex;}',
    table: () => '{display:table;}',
    'table-row': () => '{display:table-row;}',
    'table-cell': () => '{display:table-cell;}',
    hidden: () => '{display:hidden;}',
    static: () => '{position:static;}',
    fixed: () => '{position:fixed;}',
    absolute: () => '{position:absolute;}',
    relative: () => '{position:relative;}',
    sticky: () => '{position:sticky;}',
    backgroundColor: {
      variants: ({ colors }) => colors,
      css: value => `{background-color:${value};}`,
    },
    color: {
      variants: ({ colors }) => colors,
      css: value => `{color:${value};}`,
    },
    borderRadius: {
      variants: {
        none: '0',
        sm: '0.125rem',
        default: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        full: '9999px',
      },
      css: value => `{border-radius:${value};}`,
    },
    backgroundPosition: {
      variants: {
        bottom: 'bottom',
        center: 'center',
        left: 'left',
        'left-bottom': 'left bottom',
        'left-top': 'left top',
        right: 'right',
        'right-bottom': 'right bottom',
        'right-top': 'right top',
        top: 'top',
      },
      css: value => `{background-position:${value};}`,
    },
    backgroundSize: {
      variants: {
        auto: 'auto',
        cover: 'cover',
        contain: 'contain',
      },
      css: value => `{background-size:${value};}`,
    },
    borderColor: {
      variants: ({ colors }) => ({
        ...colors,
        default: colors['gray-300'],
      }),
      css: value => `{border-color:${value};}`,
    },
    overflow: {
      variants: {
        auto: 'overflow:auto',
        hidden: 'overflow:hidden',
        visible: 'overflow:visible',
        scroll: 'overflow:scroll',
        'x-auto': 'overflow-x:auto',
        'y-auto': 'overflow-y:auto',
        'x-hidden': 'overflow-x:hidden',
        'y-hidden': 'overflow-y:hidden',
        'x-visible': 'overflow-x:visible',
        'y-visible': 'overflow-y:visible',
        'x-scroll': 'overflow-x:scroll',
        'y-scroll': 'overflow-y:scroll',
      },
      css: value => `{${value};}`,
    },
    visible: () => '{visibility:visible;}',
    invisible: () => '{visibility:hidden;}',
    scrolling: {
      variants: {
        touch: 'touch',
        auto: 'auto',
      },
      css: value => `{-webkit-overflow-scrolling:${value};}`,
    },
    borderWidth: {
      variants: {
        default: '1px',
        '0': '0',
        '2': '2px',
        '4': '4px',
        '8': '8px',
      },
      css: value => `{border-width:${value};}`,
    },
    boxShadow: {
      variants: {
        xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
        none: 'none',
      },
      css: value => `{box-shadow:${value};}`,
    },
    container: {
      variants: ({ breakpoints }) => ({
        none: 'width:100%',
        ...Object.keys(breakpoints).reduce((aggr, key) => {
          aggr[key] = `max-width:${breakpoints[key]};`;

          return aggr;
        }, {} as { [key: string]: string }),
      }),
      css: value => `{${value};}`,
    },

    cursor: {
      variants: {
        auto: 'auto',
        default: 'default',
        pointer: 'pointer',
        wait: 'wait',
        text: 'text',
        move: 'move',
        'not-allowed': 'not-allowed',
      },
      css: value => `{cursor:${value};}`,
    },
    fill: {
      variants: {
        current: 'currentColor',
      },
      css: value => `{fill:${value};}`,
    },
    'flex-1': () => '{flex:1 1 0%;}',
    'flex-auto': () => '{flex:1 1 auto;}',
    'flex-initial': () => '{flex:0 1 auto;}',
    'flex-none': () => '{flex:none;}',
    flexGrow: {
      variants: {
        '0': '0',
        default: '1',
      },
      css: value => `{flex-grow:${value};}`,
    },
    flexShrink: {
      variants: {
        '0': '0',
        default: '1',
      },
      css: value => `{flex-shrink:${value};}`,
    },
    fontFamily: {
      variants: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ].join(', '),
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'].join(','),
        mono: ['Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'].join(','),
      },
      css: value => `{font-family:${value};}`,
    },
    fontSize: {
      variants: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
      },
      css: value => `{font-size:${value};}`,
    },
    fontWeight: {
      variants: {
        hairline: '100',
        thin: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      css: value => `{font-weight:${value};}`,
    },
    height: {
      variants: ({ spacing }) => ({
        auto: 'auto',
        ...spacing,
        full: '100%',
        screen: '100vh',
      }),
      css: value => `{height:${value};}`,
    },
    inset: {
      variants: {
        '0': 'top:0;right:0;bottom:0;left:0;',
        'y-0': 'top:0;bottom:0;',
        'x-0': 'right:0;left:0;',
        'y-auto': 'top:auto;bottom:auto;',
        'x-auto': 'right:auto;left:auto;',
        auto: 'top:auto;right:auto;bottom:auto;left:auto;',
      },
      css: value => `{${value}}`,
    },
    top: {
      variants: {
        '0': '0',
        auto: 'auto',
      },
      css: value => `{top:${value};}`,
    },
    right: {
      variants: {
        '0': '0',
        auto: 'auto',
      },
      css: value => `{right:${value};}`,
    },
    left: {
      variants: {
        '0': '0',
        auto: 'auto',
      },
      css: value => `{left:${value};}`,
    },
    bottom: {
      variants: {
        '0': '0',
        auto: 'auto',
      },
      css: value => `{bottom:${value};}`,
    },
    letterSpacing: {
      variants: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      css: value => `{letter-spacing:${value};}`,
    },
    lineHeight: {
      variants: {
        none: '1',
        tight: '1.25',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
        loose: '2',
      },
      css: value => `{line-height:${value};}`,
    },
    listStyleType: {
      variants: {
        none: 'none',
        disc: 'disc',
        decimal: 'decimal',
      },
      css: value => `{list-style-type:${value};}`,
    },
    float: {
      variants: {
        right: 'right',
        left: 'left',
        none: 'none',
      },
      css: value => `{float:${value};}`,
    },
    clearfix: () => '::after{content: "";display: table;clear: both;}',
    margin: {
      variants: ({ spacing }, { negative }) => ({
        auto: 'auto',
        ...spacing,
        ...negative(spacing),
      }),
      css: value => `{margin:${value}};`,
    },
    maxHeight: {
      variants: {
        full: '100%',
        screen: '100vh',
      },
      css: value => `{max-height:${value};}`,
    },
    maxWidth: {
      variants: {
        none: 'none',
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        full: '100%',
      },
      css: value => `{max-width:${value};}`,
    },
    minHeight: {
      variants: {
        '0': '0',
        full: '100%',
        screen: '100vh',
      },
      css: value => `{min-height:${value};}`,
    },
    minWidth: {
      variants: {
        '0': '0',
        full: '100%',
      },
      css: value => `{min-width:${value};}`,
    },
    object: {
      variants: {
        contain: 'object-fit:contain',
        cover: 'object-fit:cover',
        fill: 'object-fit:fill',
        none: 'object-fit:none',
        'scale-down': 'object-fit:scale-down',
        bottom: 'object-position:bottom',
        center: 'object-position:center',
        left: 'object-position:left',
        'left-bottom': 'object-position:left bottom',
        'left-top': 'object-position:left top',
        right: 'object-position:right',
        'right-bottom': 'object-position:right bottom',
        'right-top': 'object-position:right top',
        top: 'object-position:top',
      },
      css: value => `{${value};}`,
    },

    opacity: {
      variants: {
        '0': '0',
        '25': '0.25',
        '50': '0.5',
        '75': '0.75',
        '100': '1',
      },
      css: value => `{opacity:${value};}`,
    },
    order: {
      variants: {
        first: '-9999',
        last: '9999',
        none: '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
      },
      css: value => `{order:${value};}`,
    },
    padding: {
      variants: ({ spacing }) => spacing,
      css: value => `{padding:${value};}`,
    },
    placeholderColor: {
      variants: ({ colors }) => colors,
      css: value => `::placeholder{color:${value};}`,
    },
    stroke: {
      variants: {
        current: 'currentColor',
      },
      css: value => `{stroke:${value};}`,
    },
    strokeWidth: {
      variants: {
        '0': '0',
        '1': '1',
        '2': '2',
      },
      css: value => `{stroke-width:${value};}`,
    },
    width: {
      variants: ({ spacing }) => ({
        auto: 'auto',
        ...spacing,
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '2/4': '50%',
        '3/4': '75%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.666667%',
        '2/6': '33.333333%',
        '3/6': '50%',
        '4/6': '66.666667%',
        '5/6': '83.333333%',
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
        full: '100%',
        screen: '100vw',
      }),
      css: value => `{width:${value};}`,
    },
    z: {
      variants: {
        auto: 'auto',
        '0': '0',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
      },
      css: value => `{z-index:${value};}`,
    },
    gap: {
      variants: ({ spacing }) => spacing,
      css: value => `{gap:${value};}`,
    },
    rowGap: {
      variants: {},
      css: () => '',
    },
    columnGap: {
      variants: {},
      css: () => '',
    },
    gridTemplateColumns: {
      variants: {
        none: 'none',
        '1': 'repeat(1, minmax(0, 1fr))',
        '2': 'repeat(2, minmax(0, 1fr))',
        '3': 'repeat(3, minmax(0, 1fr))',
        '4': 'repeat(4, minmax(0, 1fr))',
        '5': 'repeat(5, minmax(0, 1fr))',
        '6': 'repeat(6, minmax(0, 1fr))',
        '7': 'repeat(7, minmax(0, 1fr))',
        '8': 'repeat(8, minmax(0, 1fr))',
        '9': 'repeat(9, minmax(0, 1fr))',
        '10': 'repeat(10, minmax(0, 1fr))',
        '11': 'repeat(11, minmax(0, 1fr))',
        '12': 'repeat(12, minmax(0, 1fr))',
      },
      css: value => `{grid-template-columns:${value};}`,
    },
    gridColumn: {
      variants: {
        auto: 'auto',
        'span-1': 'span 1 / span 1',
        'span-2': 'span 2 / span 2',
        'span-3': 'span 3 / span 3',
        'span-4': 'span 4 / span 4',
        'span-5': 'span 5 / span 5',
        'span-6': 'span 6 / span 6',
        'span-7': 'span 7 / span 7',
        'span-8': 'span 8 / span 8',
        'span-9': 'span 9 / span 9',
        'span-10': 'span 10 / span 10',
        'span-11': 'span 11 / span 11',
        'span-12': 'span 12 / span 12',
      },
      css: value => `{grid-column:${value};}`,
    },
    gridColumnStart: {
      variants: {
        auto: 'auto',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
        '13': '13',
      },
      css: value => `{grid-column-start:${value};}`,
    },
    gridColumnEnd: {
      variants: {
        auto: 'auto',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '6': '6',
        '7': '7',
        '8': '8',
        '9': '9',
        '10': '10',
        '11': '11',
        '12': '12',
        '13': '13',
      },
      css: value => `{grid-column-end:${value};}`,
    },
    gridTemplateRows: {
      variants: {},
      css: () => '',
    },
    gridRow: {
      variants: {},
      css: () => '',
    },
    gridRowStart: {
      variants: {},
      css: () => '',
    },
    gridRowEnd: {
      variants: {},
      css: () => '',
    },
    transformOrigin: {
      variants: {
        center: 'center',
        top: 'top',
        'top-right': 'top right',
        right: 'right',
        'bottom-right': 'bottom right',
        bottom: 'bottom',
        'bottom-left': 'bottom left',
        left: 'left',
        'top-left': 'top left',
      },
      css: value => `{transform-origin:${value};}`,
    },
    scale: {
      variants: {
        '0': '0',
        '50': '.5',
        '75': '.75',
        '90': '.9',
        '95': '.95',
        '100': '1',
        '105': '1.05',
        '110': '1.1',
        '125': '1.25',
        '150': '1.5',
      },
      css: value => `{scale:${value};}`,
    },
    rotate: {
      variants: {
        '-180': '-180deg',
        '-90': '-90deg',
        '-45': '-45deg',
        '0': '0',
        '45': '45deg',
        '90': '90deg',
        '180': '180deg',
      },
      css: value => `{rotate:${value};}`,
    },
    translate: {
      variants: ({ spacing }, { negative }) => ({
        ...spacing,
        ...negative(spacing),
        '-full': '-100%',
        '-1/2': '-50%',
        '1/2': '50%',
        full: '100%',
      }),
      css: value => `{translate:${value};}`,
    },
    skew: {
      variants: {},
      css: () => '',
    },
    transitionProperty: {
      variants: {
        none: 'none',
        all: 'all',
        default: 'background-color, border-color, color, opacity, transform',
        colors: 'background-color, border-color, color',
        opacity: 'opacity',
        transform: 'transform',
      },
      css: value => `{transition-property:${value};}`,
    },
    transitionTimingFunction: {
      variants: {
        linear: 'linear',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      css: value => `{transition-timing-function:${value};}`,
    },
    transitionDuration: {
      variants: {
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      css: value => `{transition-duration:${value};}`,
    },
  },
} as IConfig<'colors' | 'spacing' | 'breakpoints'>;
